Class {
	#name : #XdShareNullActions,
	#superclass : #XdShareProtoActions,
	#traits : 'TGtUniqueInstance',
	#classTraits : 'TGtUniqueInstance classTrait',
	#category : #'XDoc-Gt4XDocClient-Dialog - Model'
}

{ #category : #actions }
XdShareNullActions >> delete [
	"do nothing"
]

{ #category : #actions }
XdShareNullActions >> publish [
	"do nothing"
]

{ #category : #actions }
XdShareNullActions >> update [
	"do nothing"
]
