Class {
	#name : #XdProtoFile,
	#superclass : #XdObject,
	#category : #'XDoc-Core-Model'
}

{ #category : #'api - testing' }
XdProtoFile >> hasAuthor [
	<return: #Boolean>
	^ self subclassResponsibility
]

{ #category : #'api - testing' }
XdProtoFile >> hasDescription [
	<return: #Boolean>
	^ self subclassResponsibility
]

{ #category : #'api - testing' }
XdProtoFile >> hasPublicUrl [
	<return: #Boolean>
	^ self subclassResponsibility
]

{ #category : #'api - testing' }
XdProtoFile >> hasPublicationDate [
	<return: #Boolean>
	^ self subclassResponsibility
]

{ #category : #'api - testing' }
XdProtoFile >> hasTitle [
	<return: #Boolean>
	^ self subclassResponsibility
]
